INSERT INTO SECURITY_USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME) VALUES('DATTA430','$2a$12$/MTsJ/eBZqSep5KmVF6TF.DHBieMm8sOhqHPGQ4ZAqZBq5BpDqLNi','DATTA','MOGUDAMPALLI');
INSERT INTO SECURITY_USER(USERNAME,PASSWORD,FIRST_NAME,LAST_NAME) VALUES('SANTHU6833','$2a$12$/MTsJ/eBZqSep5KmVF6TF.DHBieMm8sOhqHPGQ4ZAqZBq5BpDqLNi','SANTHU','MOGUDAMPALLI');
INSERT INTO SECURITY_ROLE(ROLE) VALUES('ROLE_ADMIN');
INSERT INTO SECURITY_ROLE(ROLE) VALUES('ROLE_USER');
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES(1,1);
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES(1,2);
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES(2,1);
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES(2,2);